version: 2.1

jobs:
  build:
    working_directory: ~/circleci-demo-java-spring
    # run the steps with Docker
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    resource_class: small

    steps:
      # check out source code to working directory
      - checkout
      # restore the saved cache after the first run or if `pom.xml` has changed
      - restore_cache:
          key: eschool-{{ checksum "pom.xml" }}
      # gets the project dependencies
      - run: mvn dependency:go-offline
      # saves the project dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: eschool-{{ checksum "pom.xml" }}
      - run:
          name: change db_host
          command: sed -i -e "s|localhost|$DB_HOST|g"  ./src/main/resources/application.properties 
                   #sed -i -e "s|DATASOURCE_USERNAME:root|DATASOURCE_USERNAME:$DB_USER|g" ./src/main/resources/application.properties \
                   #sed -i -e "s|DATASOURCE_PASSWORD:root|DATASOURCE_PASSWORD:$DB_PORT|g" ./src/main/resources/application.properties
      - run:
          name: change db_usr
          command: sed -i -e "s|DATASOURCE_USERNAME:root|DATASOURCE_USERNAME:$DB_USER|g" ./src/main/resources/application.properties 
      - run:
          name: change db_passwd
          command: sed -i -e "s|DATASOURCE_PASSWORD:root|DATASOURCE_PASSWORD:$DB_PORT|g" ./src/main/resources/application.properties 
      # run unit tests
      - run: mvn package -Dtest=\!ScheduleControllerIntegrationTest*

      - store_test_results:
          # uploads the test metadata from the `target/surefire-reports` to CircleCI dashboard.
          path: target/surefire-reports

      - store_artifacts: # store the uberjar as an artifact
          path: target/eschool.jar
  deploy:
    # Use simple container for deployment
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - add_ssh_keys:
          fingerprints:
            - "20:25:aa:93:a0:58:6d:e8:38:c8:90:f2:2d:5c:1f:2b"
      # Add our server to known_hosts
      - run:
          name: fix host authenticity for deploy server
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: |
            ssh -oStrictHostKeyChecking=no $SSH_USER@$SSH_HOST "bash ./script.sh"
            
workflows:
  version: 2
  
  build_and_deploy:
    jobs:
      - build          
      - deploy:
          requires:
            - build
          # Only deploy on the master branch
          filters:
            branches:
              only: circleci-project-setup
          
                


